[package]
name = "mandelpng"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = { version = "0.4.6", features = ["serde"] }
png = "0.17.14"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
